title: "Luxor Bourommavong"
description: "Data Science Portfolio documenting my learning throughout the semester"

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

url: "https://lbouromm-sketch.github.io"
baseurl: "/Data-Science-Portfolio"

author:
  name: "Luxor Bourommavong"
  bio: "Data Science Student at UNC Charlotte, interested in Humanitarian data analysis."

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
