title: "Luxor's Data Science Portfolio"
description: "An academic and professional portfolio documenting my learning throughout my data science journey."

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

url: "https://lbouromm-sketch.github.io"
baseurl: "/Data-Science-Portfolio"

author:
  name: "Luxor Bourommavong"
  bio: "Data Science Student at UNC Charlotte. Passionate about leveraging data science techniques to solve real-world humanitarian problems and drive informed decision-making for a more sustainable future."

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

